import type { Movie } from "./catalog";

const m = (
  id: number,
  title: string,
  year: number,
  runtime: number,
  genres: string[],
  rating: number,
  cast: string[],
  directors: string[],
): Movie => ({ id, title, year, runtime, genres, rating, cast, directors });

/** 38 hand-picked movies with approximate ratings. Small and fixed, for tests only. The app loads the seeded catalog. */
export const SAMPLE_CATALOG: Movie[] = [
  m(1, "Inception", 2010, 148, ["sci-fi", "action", "thriller"], 8.8, ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"], ["Christopher Nolan"]),
  m(2, "Interstellar", 2014, 169, ["sci-fi", "drama", "adventure"], 8.7, ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"], ["Christopher Nolan"]),
  m(3, "The Dark Knight", 2008, 152, ["action", "crime", "drama"], 9.0, ["Christian Bale", "Heath Ledger", "Aaron Eckhart"], ["Christopher Nolan"]),
  m(4, "Heat", 1995, 170, ["crime", "thriller", "action"], 8.3, ["Al Pacino", "Robert De Niro", "Val Kilmer"], ["Michael Mann"]),
  m(5, "The Irishman", 2019, 209, ["crime", "drama"], 7.8, ["Robert De Niro", "Al Pacino", "Joe Pesci"], ["Martin Scorsese"]),
  m(6, "The Godfather Part II", 1974, 202, ["crime", "drama"], 9.0, ["Al Pacino", "Robert De Niro", "Robert Duvall"], ["Francis Ford Coppola"]),
  m(7, "Righteous Kill", 2008, 101, ["crime", "thriller"], 6.0, ["Robert De Niro", "Al Pacino"], ["Jon Avnet"]),
  m(8, "The Hunger Games", 2012, 142, ["action", "adventure", "sci-fi"], 7.2, ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"], ["Gary Ross"]),
  m(9, "The Hunger Games: Catching Fire", 2013, 146, ["action", "adventure", "sci-fi"], 7.5, ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"], ["Francis Lawrence"]),
  m(10, "Red Sparrow", 2018, 140, ["action", "drama", "thriller"], 6.6, ["Jennifer Lawrence", "Joel Edgerton"], ["Francis Lawrence"]),
  m(11, "X-Men: First Class", 2011, 131, ["action", "adventure", "sci-fi"], 7.7, ["James McAvoy", "Michael Fassbender", "Jennifer Lawrence"], ["Matthew Vaughn"]),
  m(12, "Silver Linings Playbook", 2012, 122, ["comedy", "drama", "romance"], 7.7, ["Bradley Cooper", "Jennifer Lawrence", "Robert De Niro"], ["David O. Russell"]),
  m(13, "Passengers", 2016, 116, ["sci-fi", "romance", "drama"], 7.0, ["Jennifer Lawrence", "Chris Pratt"], ["Morten Tyldum"]),
  m(14, "Joy", 2015, 124, ["drama", "comedy"], 6.6, ["Jennifer Lawrence", "Robert De Niro", "Bradley Cooper"], ["David O. Russell"]),
  m(15, "American Hustle", 2013, 138, ["crime", "drama"], 7.2, ["Christian Bale", "Bradley Cooper", "Amy Adams", "Jennifer Lawrence"], ["David O. Russell"]),
  m(16, "Arrival", 2016, 116, ["sci-fi", "drama", "mystery"], 7.9, ["Amy Adams", "Jeremy Renner"], ["Denis Villeneuve"]),
  m(17, "Dune", 2021, 155, ["sci-fi", "adventure", "action", "drama"], 8.0, ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya"], ["Denis Villeneuve"]),
  m(18, "Sicario", 2015, 121, ["action", "crime", "thriller"], 7.6, ["Emily Blunt", "Benicio del Toro", "Josh Brolin"], ["Denis Villeneuve"]),
  m(19, "Prisoners", 2013, 153, ["crime", "drama", "mystery", "thriller"], 8.1, ["Hugh Jackman", "Jake Gyllenhaal"], ["Denis Villeneuve"]),
  m(20, "La La Land", 2016, 128, ["comedy", "drama", "romance"], 8.0, ["Ryan Gosling", "Emma Stone"], ["Damien Chazelle"]),
  m(21, "Superbad", 2007, 113, ["comedy"], 7.6, ["Jonah Hill", "Michael Cera", "Emma Stone"], ["Greg Mottola"]),
  m(22, "Toy Story", 1995, 81, ["animation", "family", "comedy", "adventure"], 8.3, ["Tom Hanks", "Tim Allen"], ["John Lasseter"]),
  m(23, "Cast Away", 2000, 143, ["drama", "adventure"], 7.8, ["Tom Hanks", "Helen Hunt"], ["Robert Zemeckis"]),
  m(24, "Forrest Gump", 1994, 142, ["drama", "romance"], 8.8, ["Tom Hanks", "Robin Wright"], ["Robert Zemeckis"]),
  m(25, "The Matrix", 1999, 136, ["sci-fi", "action"], 8.7, ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"], ["Lana Wachowski", "Lilly Wachowski"]),
  m(26, "John Wick", 2014, 101, ["action", "thriller", "crime"], 7.4, ["Keanu Reeves", "Willem Dafoe"], ["Chad Stahelski"]),
  m(27, "Thor: Ragnarok", 2017, 130, ["action", "adventure", "comedy"], 7.9, ["Chris Hemsworth", "Tom Hiddleston", "Cate Blanchett"], ["Taika Waititi"]),
  m(28, "Rush", 2013, 123, ["drama", "action"], 8.1, ["Chris Hemsworth", "Daniel Brühl"], ["Ron Howard"]),
  m(29, "Get Out", 2017, 104, ["horror", "mystery", "thriller"], 7.8, ["Daniel Kaluuya", "Allison Williams"], ["Jordan Peele"]),
  m(30, "Hereditary", 2018, 127, ["horror", "drama", "mystery"], 7.3, ["Toni Collette", "Alex Wolff"], ["Ari Aster"]),
  m(31, "A Quiet Place", 2018, 90, ["horror", "sci-fi", "drama"], 7.5, ["Emily Blunt", "John Krasinski"], ["John Krasinski"]),
  m(32, "Paddington 2", 2017, 103, ["family", "comedy", "adventure"], 7.8, ["Ben Whishaw", "Hugh Grant", "Sally Hawkins"], ["Paul King"]),
  m(33, "Spirited Away", 2001, 125, ["animation", "fantasy", "family", "adventure"], 8.6, [], ["Hayao Miyazaki"]),
  m(34, "Knives Out", 2019, 130, ["comedy", "crime", "mystery"], 7.9, ["Daniel Craig", "Ana de Armas", "Chris Evans"], ["Rian Johnson"]),
  m(35, "The Wolf of Wall Street", 2013, 180, ["comedy", "crime"], 8.2, ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"], ["Martin Scorsese"]),
  m(36, "Mad Max: Fury Road", 2015, 120, ["action", "adventure", "sci-fi"], 8.1, ["Tom Hardy", "Charlize Theron"], ["George Miller"]),
  m(37, "Taxi Driver", 1976, 114, ["crime", "drama"], 8.2, ["Robert De Niro", "Jodie Foster"], ["Martin Scorsese"]),
  m(38, "Scarface", 1983, 170, ["crime", "drama"], 8.3, ["Al Pacino", "Michelle Pfeiffer"], ["Brian De Palma"]),
];
